version: "3.9"
services:
  mssql:
    build:
      context: ./docker/mssql
    container_name: mrjb-debezium-mssql
    ports:
      - "1443:1443"
  zookeeper:
    image: debezium/zookeeper
    container_name: mrjb-debezium-zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka
    container_name: mrjb-debezium-kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  debezium-connect:
    build:
      context: ./docker/connect/
      dockerfile: Dockerfile
    container_name: mrjb-debezium-connect
    ports:
      - 8083:8083
    depends_on:
      - kafka
    networks:
      - mrjb-debezium-network
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium-configs
      - OFFSET_STORAGE_TOPIC=debezium-offsets
      - STATUS_STORAGE_TOPIC=debezium-statuses
      # ssl
      - CONNECT_LISTENERS=http://0.0.0.0:8083,https://0.0.0.0:8084
      - CONNECT_LISTENERS_HTTPS_SSL_ENABLE_PROTOCOL=TLSv1.2
      - CONNECT_LISTENERS_HTTPS_SSL_KEY_PASSWORD=${KEY_PASSWORD}
      - CONNECT_LISTENERS_HTTPS_SSL_KEYSTORE_LOCATION=/keystore/debezium.keystore.jks
      - CONNECT_LISTENERS_HTTPS_SSL_KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - CONNECT_LISTENERS_HTTPS_SSL_TRUSTSTORE_LOCATION=/keystore/debezium.truststore.jks
      - CONNECT_LISTENERS_HTTPS_SSL_TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      # basic auth
      - CONNECT_REST_EXTENSION_CLASSES=org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension
      - KAFKA_OPTS=-Djava.security.auth.login.config=/kafka/config/debezium_jaas.conf
      # log level
      - LOG_LEVEL=ERROR
  debezium-ui:
    image: debezium/debezium-ui
    container_name: mrjb-debezium-ui
    ports:
      - 8080:8080
    environment:
      - KAFKA_CONNECT_URIS=http://debezium-connect:8083
    depends_on:
      - debezium-connect
    networks:
      - mrjb-debezium-network
networks:
  mrjb-debezium-network:

