version: "3.9"
services:
  mssql:
    build:
      context: ./docker/mssql
    container_name: mrjb-debezium-mssql
    ports:
      - "1433:1433"
    # networks:
    #   - mrjb-debezium-network
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=RqrhWH5HmwGc6mEF
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    hostname: zookeeper
    container_name: mrjb-debezium-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.3.1
    hostname: broker
    container_name: mrjb-debezium-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      # KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  debezium-connect:
    # image: mrjb/debezium-connect:${DEBEZIUM_VERSION}
    build:      
      context: ./docker/connect/
      dockerfile: Dockerfile
      args:
        - DEBEZIUM_VERSION=${DEBEZIUM_VERSION}
        - KEYSTORE_PASSWORD=${KEY_PASSWORD}
        - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
        - KEY_PASSWORD=${KEY_PASSWORD}
    container_name: mrjb-debezium-connect
    ports:
      - 8083:8083
      - 8084:8084
    depends_on:
      - kafka
      - mssql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s      
    # restarts: on-failure
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium-configs
      - OFFSET_STORAGE_TOPIC=debezium-offsets
      - STATUS_STORAGE_TOPIC=debezium-statuses
      # # ssl
      # - CONNECT_LISTENERS=http://0.0.0.0:8083,https://0.0.0.0:8084
      # - CONNECT_LISTENERS_HTTPS_SSL_ENABLE_PROTOCOL=TLSv1.2
      # - CONNECT_LISTENERS_HTTPS_SSL_KEY_PASSWORD=${KEY_PASSWORD}
      # - CONNECT_LISTENERS_HTTPS_SSL_KEYSTORE_LOCATION=/keystores/keystore.jks
      # - CONNECT_LISTENERS_HTTPS_SSL_KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      # - CONNECT_LISTENERS_HTTPS_SSL_TRUSTSTORE_LOCATION=/keystores/truststore.jks
      # - CONNECT_LISTENERS_HTTPS_SSL_TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      # # basic auth
      # - CONNECT_REST_EXTENSION_CLASSES=org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension
      # - KAFKA_OPTS=-Djava.security.auth.login.config=/kafka/config/debezium_jaas.conf
      # log level
      - LOG_LEVEL=ERROR
    volumes:
     - ./history:/kafka/connect/history/ # windows

  debezium-ui:
    image: debezium/debezium-ui
    container_name: mrjb-debezium-ui
    ports:
      - 8080:8080
    environment:
      - KAFKA_CONNECT_URIS=http://debezium-connect:8083
    depends_on:
      - debezium-connect
      - kafka
      - mssql
    # networks:
    #   - mrjb-debezium-network
# networks:
#   mrjb-debezium-network:

